### ISSUE TITLE
Imports with mismatched types

### ISSUE THREAD

**Issue by hiimkosu1** [pawel-id/bir1#16]
After migrating to TypeScript the imports are still with .js extension. It's causing problem that all imports are giving the same error: 
**Cannot find module 'bir1' or its corresponding type declarations.**

**Comment by pawel-id** [comment]
Please provide minimal reproducible example or explain step by step how to get this error. Thanks.

**Comment by hiimkosu1** [comment]
![Screenshot 2024-03-18 105326](https://github.com/pawel-id/bir1/assets/135039184/372920bd-8e76-4dd4-95a0-d5c12ee7e5d6)

This problem started after updating bir1 from version 2.0.2 to 3.0.1.

**Comment by pawel-id** [comment]
it might be because of missing type declarations. Please check version bir1@3.0.2
